platform :ios, '8.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'LCNetworkingDemo' do

pod 'LCNetworking', :path => '../'
pod 'Masonry', '1.1.0'
pod 'AFNetworking','3.2.1'
pod 'SDWebImage','5.1.1'
pod 'YYImage', '1.0.4'

end
